name: build-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - jupyter_server
  - nbformat
  - jupyterlab
  - notebook
  - jupytext
  - ipywidgets>=8.1.1,<9
  - plotly>=5,<6
  - jupyterlab_filesystem_access
  - jupyterlab-night
  - jupyterlite-xeus>=0.1.5,<0.2
  - jupyterlite-core=0.3.0
