name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlab-night
  - jupyterlite-xeus>=0.1.2,<0.2
  - jupyterlite-core>=0.2,<0.3
  - pip:
    - libarchive-c
    - jupyterlite-core==0.3.0rc1    
    - ipywidgets>=8.1
    - jupyterlab-fasta>=3,<4
    - jupyterlab-geojson>=3,<4
    - plotly>=5,<6
    - jupyterlab-cell-flash
    - jupyterlite-core==0.3.0rc1
