name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - python-libarchive-c
  - jupyterlab-night
  - jupyter_server
  #- jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus >=0.1.2,<0.2
  pip:
    #- voici
    - jupyterlite-xeus-python
    - jupyterlite-core==0.3.0rc1
    - jupyterlab_miami_nights>=0.4.0
  
