name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - python-libarchive-c
  - jupyterlab-night
  - jupyterlab-geojson
  - jupyterlab-fasta
  - jupyter_server
  - jupyterlab_server
  - pydata-sphinx-theme
  - myst-parser
  - docutils
  - sphinx
  - black
  - voici
  - pip:
      - jupyterlite-core[lab]>=0.2.0,<0.3.0
      - jupyterlite-xeus>=0.1.5,<0.2
