name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - black
  - jupyter_server
  - python-libarchive-c
  - jupyterlab-night
  - jupyterlab-geojson
  - jupyterlab-fasta
  - jupyterlite-xeus>=0.1.5,<0.2
  - jupyterlite-core>=0.2,<0.3
