name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlab-night
  - jupyterlab-geojson
  - jupyterlab-fasta
  - jupyterlite-core>=0.2.0,<0.3.0
  - jupyterlite-xeus>=0.1.5,<0.2
