name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server  # resolved to v2.11.2
  - jupyterlite-core  # resolved to v0.2.1
  - pip
  - pip:
    - --pre
    - jupyterlite-xeus-python==1.0.0a3
