name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - python-libarchive-c
  - jupyterlab-night
  - jupyterlab-geojson
  - jupyterlab-fasta
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - jupyterlite-xeus>=0.1.2,<0.2
