name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlab-night
  - jupyterlab-fasta>=3,<4
  - jupyterlab-geojson>=3,<4
  - jupyterlite-xeus>=0.1.2,<0.2
  - jupyterlite-core>=0.2,<0.3
