name: build-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - jupyter_server
  - jupytext
  - black
  - ipywidgets>=8.1.1,<9
  - plotly>=5,<6
  - jupyterlab-night
  - python-libarchive-c
  - jupyterlite-xeus>=0.1.5,<0.2
  - jupyterlite-core=0.3.0
