name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - python-libarchive-c
  - jupyterlab-night
  - jupyterlab_miami_nights
  - jupyterlab-geojson
  - jupyterlab-fasta
  - jupyter_server
  - jupyterlite-xeus >=0.1.2,<0.2
  - jupyterlite-core >=0.2,<0.3
  
