name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlab-night
  - jupyterlab-geojson
  - jupyterlab-fasta
  - jupyterlite-xeus>=0.1.5,<0.2
  - pip:
    - jupyterlite-core==0.3.0rc1
