name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core>=0.2.0,<0.3.0
  - jupyterlite-xeus>=0.1.2,<0.2
  - cmake 
  - xeus 
  - xeus-zmq 
  - nlohmann_json 
  - cppzmq 
  - xtl 
  - pybind11 
  - pybind11_json 
  - xeus-python-shell 
  - jupyterlab
