name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - python-libarchive-c
  - empack >=3,<4
  - jupyterlite-core
  - jupyterlite-xeus
  - ipywidgets
  - ipyvuetify
  - jupyterlab-night
  - jupyterlab_execute_time
