name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - python-libarchive-c
  - jupyterlab-night
  - jupyterlab_miami_nights
  - jupyter_server
  - jupyterlite-xeus >=0.1.2,<0.2
  - jupyterlite-core==0.3.0rc1
  
