name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  #- geopy
  #- ipython
  #- statsmodels
  #- itables==1.7.0
  #- missingno==0.4.2
  #- openpyxl==3.0.9
  - plotly
  #- pycountry
  #- pyjanitor
  #- pyxlsb==1.0.10
  - ipycanvas
  - ipympl
  - ipydatagrid
  - numpy
  - matplotlib
  - sqlalchemy
  - seaborn
  - pandas
  - scikit-learn
  

