name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - ipywidgets
  - ipycanvas
  - altair
  - astropy
  - biopython
  - black
  - country_converter
  - dill
  - docutils
  - geopy
  - isort
  - itables
  - matplotlib
  - missingno
  - openpyxl
  - peewee
  - plotly
  - pycountry
  - pyjanitor
  - python-dotenv
  - pyxlsb
  - scikit-image
  - sqlite-utils
  - sqlalchemy
  - squarify
  - sweetviz
