name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - altair
  - astropy
  - async-lru
  - awkward-cpp
  - biopython
  - black
  - boost-histogram
  - cftime
  - country_converter
  - dill
  - docutils
  - eigen
  - geopy
  - ifaddr
  - isort
  - itables
  - logbook
  - matplotlib
  - missingno
  - munch
  - openpyxl
  - peewee
  - plotly
  - protobuf
  - pybind11
  - pycountry
  - pyjanitor
  - pytest
  - python-dotenv
  - pythran
  - pyxlsb
  - scikit-image
  - sqlite-utils
  - sqlalchemy
  - pyomo
  - lightgbm
  - geopandas
  - squarify
  - sweetviz
  - swiglpk
  - traits
  - wrapt
  - zarr
