name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - geopy
  - ipython==8.21.0
  - isort
  - statsmodels==0.14.1
  - itables
  - missingno
  - openpyxl
  - plotly
  - pycountry
  - pyjanitor
  - pyxlsb
  - ipycanvas
  - ipympl
  - ipydatagrid
  - numpy==1.25.2
  - matplotlib
  - sqlite
  - sqlalchemy
  - seaborn
  - pandas
  - scikit-learn
  

