name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - itables
  - ipywidgets
  - aiomultiprocess >=0.9.1,<0.10
  - aiorun >=2024.8.1,<2025
  - aiorwlock >=1.3.0,<2
  - alabaster >=1.0.0,<2
  - anyascii >=0.3.2,<0.4
  - appdirs >=1.4.4,<2
  - argh >=0.31.3,<0.32
  - asttokens >=2.4.1,<3
  - asyncstdlib >=3.12.5,<4
  - attrs >=23.2.0,<25
  - autocommand >=2.2.2,<3
  - backcall >=0.2.0,<0.3
  - backoff >=2.2.1,<3
  - base58 >=2.1.1,<3
  - beartype >=0.18.5,<0.19
  - beniget >=0.4.2.post1,<0.5
  - bidict >=0.23.1,<0.24
  - bleach >=6.1.0,<7
  - blinker >=1.8.2,<2
  - branca >=0.7.2,<0.8
  - cachelib >=0.13.0,<0.14
  - cachetools >=5.3.3,<6
  - casefy >=0.1.7,<0.2
  - cffi >=1.15.0,<1.17
  - cfgv >=3.3.1,<4
  - chevron >=0.14.0,<0.15
  - circuitbreaker >=2.0.0,<3
  - click >=7,<8.2
  - cloudpickle >=3.0.0,<4
  - colorama >=0.4.6,<0.5
  - colorhash >=1.0.4,<3
  - comm >=0.2.2,<0.3
  - commonmark >=0.9.1,<0.10
  - configparser >=7.1.0,<8
  - conllu >=5.0.1,<6
  - construct >=2.10.70,<3
  - contextlib2 >=21.6.0,<22
  - contourpy >=1.2.1,<2
  - crccheck >=1.3.0,<2
  - cycler >=0.12.1,<0.13
  - dacite >=1.8.1,<2
  - dataclassy >=1.0.1,<2
  - decorator >=5.1.1,<6
  - deepdiff >=8.0.1,<9
  - deepmerge >=2.0,<3
  - defusedxml >=0.7.1,<0.8
  - dictdiffer >=0.9.0,<0.10
  - dicttoxml >=1.7.16,<2
  - dill >=0.3.8,<0.4
  - diskcache >=5.6.3,<6
  - docutils >=0.18.1,<0.22
  - doit >=0.36.0,<0.37
  - dominate >=2.9.1,<3
  - dpath >=2.2.0,<3
  - dpkt >=1.9.8,<2
  - dynaconf >=3.2.6,<4
  - editables >=0.5,<0.6
  - einops >=0.8.0,<0.9
  - elementpath >=4.4.0,<5
  - empack >=3,<4
  - entrypoints >=0.4,<0.5
  - envier >=0.4.0,<0.5
  - eradicate >=2.3.0,<3
  - escapism >=1.0.1,<2
  - everett >=3.3.0,<4
  - exceptiongroup >=1.2.1,<2
  - execnet >=2.1.1,<3
  - executing >=2.0.1,<3
  - expandvars >=0.9.0,<0.10
  - exrex >=0.11.0,<0.12
  - fastprogress >=1.0.3,<2
  - filetype >=1.2.0,<2
  - fqdn >=1.5.1,<2
  - fsspec >=2024.3.1,<2025
  - funcy >=2.0,<3
  - gast >=0.5.5,<0.6
  - giturlparse >=0.12.0,<0.13
  - haversine >=2.8.1,<3
  - hexbytes >=1.2.1,<2
  - hstspreload >=2024.8.1,<2025
  - html5lib >=1.1,<2
  - html5tagger >=1.3.0,<2
  - humanize >=4.10.0,<5
  - icdiff >=2.0.7,<3
  - idna >=3.7,<4
  - ijson >=3.1.1,<4
  - imageio >=2.34.1,<3
  - imagesize >=1.4.1,<2
  - immutabledict >=4.2.0,<5
  - inflection >=0.5.1,<0.6
  - injector >=0.22.0,<0.23
  - intelhex >=2.3.0,<3
  - invoke >=2.2.0,<3
  - iso3166 >=2.1.1,<3
  - isort >=5.13.2,<6
  - itemadapter >=0.9.0,<0.10
  - itsdangerous >=2.2.0,<3
  - jedi >=0.19.1,<0.20
  - jmespath >=1.0.1,<2
  - joblib >=1.4.2,<2
  - json5 >=0.9.25,<0.10
  - jsondiff >=2.0.0,<3
  - jsonpickle >=3.3.0,<4
  - jsonschema >=4.17.3,<4.22
  - junitparser >=3.2.0,<4
  - lark >=1.2.2,<2
  - locket >=1.0.0,<2
  - looseversion >=1.3.0,<2
  - lxml >=4.9.4,<6
  - makefun >=1.15.4,<2
  - markdown2 >=2.5.0,<3
  - marko >=2.1.2,<3
  - mdurl >=0.1.2,<0.2
  - mergedeep >=1.3.4,<2
  - mistletoe >=1.4.0,<2
  - mistune >=3.0.2,<4
  - mock >=5.1.0,<6
  - mpmath >=1.3.0,<2
  - multimethod >=1.12,<2
  - multipledispatch >=0.6.0,<1.1
  - munch >=4.0.0,<5
  - natsort >=8.4.0,<9
  - networkx >=3.2,<4
  - numpy >=1.25.2,<2
  - objsize >=0.7.0,<0.8
  - olefile >=0.47,<0.48
  - openpyxl >=3.0.9,<3.1.5
  - overrides >=7.7.0,<8
  - packaging >=23.2,<25
  - pandas >=1.5.3,<2
  - param >=2.1.1,<3
  - parse >=1.20.2,<2
  - parsedatetime >=2.6,<3
  - parso >=0.8.4,<0.9
  - pastel >=0.2.1,<0.3
  - pathable >=0.4.3,<0.5
  - patsy >=0.5.6,<0.6
  - pexpect >=4.9.0,<5
  - pgzip >=0.3.5,<0.4
  - pickleshare >=0.7.5,<0.8
  - plac >=1.4.3,<2
  - platformdirs >=4.2.2,<5
  - plotext >=5.2.8,<6
  - plotly >=5.24.0,<6
  - polib >=1.2.0,<2
  - polling2 >=0.5.0,<0.6
  - polyline >=2.0.2,<3
  - pony >=0.7.18,<0.8
  - pox >=0.3.4,<0.4
  - py >=1.11.0,<2
  - py4j >=0.10.9.7,<0.11
  - pycountry >=24.6.1,<25
  - pycparser >=2.22,<3
  - pydyf >=0.11.0,<0.12
  - pyfakefs >=5.6.0,<6
  - pygtrie >=2.5.0,<3
  - pyparsing >=3.1.2,<4
  - pyrsistent >=0.18.1,<0.21
  - pysbd >=0.3.4,<0.4
  - pystache >=0.6.5,<0.7
  - pytz >=2024.1,<2025
  - pytzdata >=2020.1,<2021
  - pyudev >=0.24.3,<0.25
  - pyxlsb >=1.0.10,<2
  - queuelib >=1.7.0,<2
  - redo >=2.0.4,<3
  - regex >=2022.1.18,<2025
  - requests >=2.31.0
  - resolvelib >=1.0.1,<2
  - rfc3986 >=2.0.0,<3
  - rich >=13.7.1,<14
  - rstr >=3.2.2,<4
  - runtype >=0.5.0,<0.6
  - s3transfer >=0.10.2,<0.11
  - schedula >=1.5.19,<2
  - schedule >=1.2.2,<2
  - schema >=0.7.7,<0.8
  - scipy >=1.11.1
  - scooby >=0.10.0,<0.11
  - semver >=3.0.2,<4
  - shortuuid >=1.0.13,<2
  - simpervisor >=1.0.0,<2
  - simpleeval >=0.9.13,<0.10
  - simpy >=4.1.1,<5
  - six >=1.16.0,<2
  - slicer >=0.0.8,<0.0.9
  - snowballstemmer >=2.2.0,<3
  - soupsieve >=2.5,<3
  - sqlglot >=25.18.0,<26
  - sqlparams >=6.1.0,<7
  - statsd >=4.0.1,<5
  - statsmodels >=0.14.1,<0.15
  - stdlibs >=2024.1.28,<2025
  - striprtf >=0.0.26,<0.0.27
  - structlog >=24.4.0,<25
  - svgwrite >=1.4.3,<2
  - tblib >=3.0.0,<4
  - tenacity >=9.0.0,<10
  - terminaltables >=3.1.10,<4
  - texttable >=1.7.0,<2
  - threadpoolctl >=3.4.0,<4
  - throttler >=1.2.2,<2
  - tinydb >=4.8.0,<5
  - tomli >=2.0.1,<3
  - toolz >=0.12.1,<0.13
  - tqdm >=4.66.2,<4.67
  - traceml >=1.1.5,<2
  - traitlets >=5.14.3,<6
  - traittypes >=0.2.1,<0.3
  - ttp >=0.9.5,<0.10
  - txaio >=23.1.1,<24
  - typer >=0.10.0,<0.12
  - uncertainties >=3.1.7,<4
  - uritemplate >=4.1.1,<5
  - validators >=0.33.0,<0.34
  - venusian >=3.1.0,<4
  - versioneer >=0.29,<0.30
  - vine >=5.1.0,<6
  - voluptuous >=0.15.2,<0.16
  - waitress >=3.0.0,<4
  - wcwidth >=0.2.13,<0.3
  - webencodings >=0.5.1,<0.6
  - wheel >=0.44.0,<0.45
  - wrapt >=1.16.0,<2
  - xarray >=2024.3.0,<2025
  - xlrd >=2.0.1,<3
  - xmltodict >=0.13.0,<0.14
  - xyzservices >=2024.4.0,<2025
  - zipp >=3.20.1,<4
 











 
