name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - altair
  - bqplot
  - geopy
  - ipycanvas
  - ipydatagrid
  - ipympl
  - matplotlib
  - missingno
  - numpy
  - openpyxl
  - pandas
  - ipywidgets
  - folium
  - jupyterlab_widgets
  - plotly
  - pycountry
  - pyxlsb
  - scikit-learn
  - jupytext
  - scipy
  - seaborn
  - sqlalchemy
  - xeus-python
  

