name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - black 
  - country_converter 
  - geopy 
 # - hvplot 
  - isort 
  - itables 
  - jupytext 
  - missingno 
  - openpyxl 
  - plotly 
  - pycountry 
  - pyjanitor 
  - python-dotenv 
  - pyxlsb 
  - scikit-learn 
  - sqlalchemy 
  - squarify 
  - sweetviz
#  - httpx#  - ipycanvas
#  - ipydatagrid
#  - ipyleaflet
#  - ipympl
#  - ipywidgets
#  - isort
#  - itables
#  - lxml
#  - matplotlib
#  - missingno
#  - numpy
#  - openpyxl
#  - pandas
#  - peewee
#  - pillow
#  - plotly
#  - pycountry
#  - pyjanitor
#  - python
#  - python-dotenv
#  - python-tzdata
#  - pyviz_comms
#  - pyxlsb
#  - requests
#  - scikit-image
#  - scikit-learn
#  - scipy
#  - seaborn
#  - sqlalchemy
#  - sqlite
#  - sqlite-utils
#  - squarify
#  - statsmodels
#  - sweetviz
#  - vega_datasets
#  - xarray
  

