name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - ipywidgets
  - ipycanvas
  - astropy
  - biopython
  - black
  - country_converter
  - dill
  - docutils
  - geopy
  - isort
  - itables
  - matplotlib
  - missingno
  - openpyxl
  - peewee
  - plotly
  - pycountry
  - pyjanitor
  - python-dotenv
  - pyxlsb
  - scikit-image
  - sqlite-utils
  - sqlalchemy
  - squarify
  - sweetviz
  - altair
  - black
  - bokeh
  - bqplot
  - folium
  - httpx
  - ipycanvas
  - ipydatagrid
  - ipyleaflet
  - ipympl
  - ipywidgets
  - lxml
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - panel
  - peewee
  - pillow
  - plotly
  - plotnine
  - python
  - python-tzdata
  - pyviz_comms
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - sqlite
  - statsmodels
  - vega_datasets
  - xarray

