name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - altair 
  - astropy 
  - async-lru 
  - awkward-cpp 
  - biopython 
  - boost-histogram 
  - cftime 
  - click-default-group-wheel 
  - datasette 
  - dill 
  - docutils 
  - dtale 
  - eigen 
  - flet 
  - geopandas 
  - gmpy2 
  - hvplot 
  - ibis-framework 
  - ifaddr 
  - ipyleaflet 
  - ipympl 
  - isort 
  - jupyter 
  - jupyter-cache 
  - jupyter-lsp 
  - jupyterlab 
  - jupyter_bokeh 
  - logbook 
  - matplotlib 
  - mkdocs-jupyter 
  - munch 
  - mypy_extensions 
  - nbdev 
  - nicegui 
  - peewee 
  - protobuf 
  - pugixml 
  - pybind11 
  - pyomo 
  - pytest 
  - pythran 
  - qutip 
  - readtime 
  - scikit-image 
  - spatialgeometry 
  - stats_can 
  - swiglpk 
  - traits 
  - unicodedata2 
  - vizro 
  - wrapt 
  - zarr 
  - python-kaleido
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.2.0,<0.3.0
  - pip:
    - jupyterlite-xeus>=0.1.2,<0.2
