name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - altair
  - bqplot
  - geopy
  - ipycanvas
  - ipydatagrid
  - ipympl
  - jupyter-server
  - jupyterlite-core
  - jupyterlite-xeus
  - matplotlib
  - missingno
  - numpy
  - openpyxl
  - pandas
  - plotly
  - pycountry
  - pyxlsb
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - xeus-python
  

