name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - altair
  - bqplot
  - geopy
  - ipycanvas
  - ipydatagrid
  - ipympl
  - matplotlib
  - missingno
  - numpy
  - openpyxl
  - pandas
  - ipywidgets>=8.1
  - folium
  - plotly
  - pycountry
  - pyxlsb
  - scikit-learn
  - jupytext
  - scipy
  - seaborn
  - sqlalchemy
  # more packages
  - ipyleaflet
  - jupyterlab-night
  - jupyterlab-geojson
  - jupyterlab-fasta
  - unicodedata2
  - tabulate
  - spatialgeometry
  - statsmodels
  - scikit-image
  - peewee
  - pillow
  - astropy
