name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - xeus-python
  - jupyterlite-xeus>=0.1.5,<0.2
  - geopy 
  - isort 
  - itables 
  - missingno 
  - openpyxl
  - bqplot
  - plotly==5.18.0
  - ipywidgets==8.1.1
  - pycountry 
  - pyjanitor 
  - python-dotenv 
  - pyxlsb 
  - scikit-learn 
  - sqlalchemy 
  - squarify 
  - sweetviz
  - ipycanvas
  - numpy
  - matplotlib
  - seaborn
  - plotnine
  - pandas <2
  - statsmodels==0.14.1
  - scipy
  - sqlite
  - altair
  - ipympl
  - ipyleaflet
  - ipydatagrid
  - ipycanvas
  - vega_datasets
  - black
  - xarray
  - httpx
  

