name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge/noarch
dependencies:
  - xeus-python
  - geopy 
  - isort 
  - itables 
  - missingno 
  - openpyxl
  - plotly
  - pycountry 
  - pyjanitor 
  - python-dotenv 
  - pyxlsb 
  - sqlalchemy 
  - squarify 
  - sweetviz
  - ipycanvas
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - ipympl
  - ipydatagrid
  - ipycanvas
  - requests
  

