name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - openpyxl
  - bqplot
  - ipydatagrid
  - nbformat
  - numpy
  - matplotlib
  - ipywidgets
  - pandas
  - requests
  - treelib
  - knack
  - retrying
  - rfc3986-validator
  - azure-mgmt-cosmosdb
  - resolvelib
  - django-axes
  - azure-servicebus
  - flake8-colors
  - drf-spectacular-sidecar
  - pygtrie
  - azure-data-tables
  - limits
  - croniter
  - googleapis-common-protos
  - findpython
  - catalogue
  - imagesize
  - pyparsing
  - emoji
  - fake-useragent
  - requests-toolbelt
  - sortedcontainers
  - autodocsumm
  - flake8-multiline-containers
  - requests-mock
  - flaky
  - django-structlog
  - histoprint
  - flask-admin
  - configparser
  - face
  - apispec-webframeworks
  - azure-synapse-artifacts
  - dill
  - flask-login
  - constructs
  - ffn
  - yamllint
  - cmaes
  - marshmallow-oneofschema
  - typing-extensions
  - pycparser
  - configobj
  - tomlkit
  - django-auditlog
  - voluptuous
  - networkx
  - incremental
  - flask-jwt-extended
  - mergedeep
  - xyzservices
  - interrogate
  - azure-storage-file-datalake
  - python-json-logger
  - pbr
  - pytzdata
  - lark-parser
  - geomet
  - tqdm
  - twine
  - cfgv
  - confuse
  - boltons
  - pkginfo
  - flask-sqlalchemy
  - bitstring
  - smmap
  - fredapi
  - imgviz
  - w3lib
  - azure-cosmos
  - asteval
  - rich
  - ptyprocess
  - aws-sam-translator
  - fonttools
  - faker
  - django-recaptcha
  - trove-classifiers
  - flake8-docstrings
  - flake8
  - iso8601
  - msrest
  - markupsafe
  - html5tagger
  - django-debug-toolbar
  - djangorestframework
  - identify
  - openai
  - marshmallow-sqlalchemy
  - azure-keyvault-keys
  - aenum
  - simple-salesforce
  - funcsigs
  - apispec
  - httplib2
  - pymysql
  - gymnasium
  - cytoolz
  - dateparser
  - py-cpuinfo
  - django-reversion
  - azure-mgmt-containerregistry
  - loguru
  - django-htmx
  - wtforms
  - elastic-transport
  - html2text
  - extension-helpers
  - async-timeout
  - dom-toml
  - pygments
  - access
  - pytest-django
  - azure-graphrbac
  - distro
  - deprecation
  - dnslib
  - pyasn1-modules
  - chardet
  - joblib
  - hvac
  - cheroot
  - griffe
  - brotli
  - google-auth-httplib2
  - asyncssh
  - asgiref
  - pytest-mock
  - termcolor
  - matplotlib-inline
  - azure-mgmt-dns
  - s3transfer
  - monotonic
  - django-storages
  - sniffio
  - ariadne
  - delocate
  - lunr
  - jsonpatch
  - branca
  - itemloaders
  - cookiecutter
  - pytz
  - mccabe
  - pyxdg
  - office365-rest-python-client
  - pastel
  - charset-normalizer
  - pendulum
  - marshmallow-jsonapi
  - prompt-toolkit
  - jedi
  - azure-keyvault-certificates
  - partd
  - click-aliases
  - progressbar2
  - regex
  - affine
  - cloudant
  - retry
  - lxml
  - pywinrm
  - fido2
  - cfn-flip
  - azure-identity
  - autoflake
  - azure-storage-blob
  - django-health-check
  - attrs
  - bayesian-optimization
  - dateutils
  - isoduration
  - django
  - django-maintenance-mode
  - entrypoints
  - pytesseract
  - stevedore
  - findspark
  - fs
  - dash
  - email-validator
  - robotframework
  - django-linear-migrations
  - azure-storage-common
  - cattrs
  - django-organizations
  - django-revproxy
  - jsonpath-ng
  - dictpath
  - django-import-export
  - zeep
  - patsy
  - jsonfield
  - sentry-sdk
  - dictdiffer
  - pytest-forked
  - pyrsistent
  - django-annoying
  - humanfriendly
  - hyperframe
  - crashtest
  - pyyaml
  - django-jinja
  - consolekit
  - html-text
  - waitress
  - azure-keyvault-secrets
  - isodate
  - cachelib
  - imageio
  - azure-common
  - dnspython
  - awxkit
  - toml
  - babel
  - django-nose
  - shellingham
  - backcall
  - elasticsearch
  - asdf-astropy
  - django-redis
  - execnet
  - flake8-builtins
  - slacker
  - execnb
  - sqlparse
  - semver
  - augmentor
  - flake8-import-order
  - django-json-widget
  - azure-mgmt-msi
  - colorama
  - certifi
  - django-browser-reload
  - sphinx
  - cssutils
  - pickleshare
  - azure-core
  - unidecode
  - django-log-request-id
  - aioconsole
  - datefinder
  - fsspec
  - portalocker
  - asgi-lifespan
  - requests-oauthlib
  - mock
  - oscrypto
  - shortuuid
  - jmespath
  - aws-xray-sdk
  - typeguard
  - pexpect
  - text-unidecode
  - easy-thumbnails
  - virtualenv-clone
  - azure-mgmt-authorization
  - django-formtools
  - outcome
  - drf-spectacular
  - tabulate
  - azure-mgmt-resource
  - validators
  - user-agents
  - azure-nspkg
  - slicer
  - rsa
  - pre-commit
  - mdit-py-plugins
  - pydruid
  - python-editor
  - wasabi
  - ipdb
  - azure-mgmt-containerservice
  - dacite
  - autopage
  - anyio
  - autobahn
  - ghapi
  - markdownify
  - service-identity
  - soupsieve
  - rfc3339-validator
  - azure-mgmt-storage
  - jsonpointer
  - decorator
  - pytest
  - poetry-core
  - django-ses
  - itemadapter
  - click-option-group
  - comm
  - click-plugins
  - werkzeug
  - flask-wtf
  - django-extensions
  - dot2tex
  - google-api-core
  - python-slugify
  - altair
  - traitlets
  - emcee
  - hyperlink
  - flake8-comprehensions
  - keras-preprocessing
  - widgetsnbextension
  - apeye
  - conjure-python-client
  - nltk
  - debtcollector
  - webob
  - altgraph
  - django-flags
  - twilio
  - jinja2
  - munch
  - asdf-coordinates-schemas
  - py4j
  - requests-futures
  - hubspot-api-client
  - jdcal
  - mako
  - social-auth-app-django
  - webencodings
  - flake8-functions
  - djangorestframework-stubs
  - defusedxml
  - globus-sdk
  - future
  - click-help-colors
  - tensorboard-plugin-wit
  - django-taggit
  - google-auth
  - pyflakes
  - applicationinsights
  - jsondiff
  - concurrent-log-handler
  - importlib-metadata
  - raven
  - requests-file
  - xlrd
  - nbformat
  - appdirs
  - flake8-executable
  - jwcrypto
  - netaddr
  - pytest-xdist
  - flask-limiter
  - starlette
  - imbalanced-learn
  - django-cors-headers
  - kml2geojson
  - elementpath
  - jsonpickle
  - fakeredis
  - packaging
  - protego
  - azure-mgmt-monitor
  - scipy
  - flask-talisman
  - wsproto
  - cssselect
  - boxsdk
  - threadpoolctl
  - python-dateutil
  - bibtexparser
  - oauthlib
  - distlib
  - amundsen-rds
  - gitpython
  - python-jose
  - doit
  - nodeenv
  - jsonschema
  - django-colorfield
  - six
  - pyathena
  - pg8000
  - virtualenv
  - clize
  - fpdf2
  - qtpy
  - apscheduler
  - requests
  - deprecated
  - lmfit
  - cloudpickle
  - arrow
  - tablib
  - cycler
  - ply
  - gql
  - azure-mgmt-redis
  - django-dbbackup
  - click-repl
  - httpx
  - slackclient
  - azure-mgmt-batch
  - headerparser
  - flask-restx
  - pandas
  - docker-image-py
  - azure-mgmt-keyvault
  - tzdata
  - responses
  - automat
  - pastedeploy
  - pluggy
  - flake8-bugbear
  - flake8-black
  - uritemplate
  - pep517
  - filelock
  - django-cachalot
  - asttokens
  - asdf
  - google-pasta
  - async-lru
  - dominate
  - deprecat
  - boto3
  - gidgethub
  - cryptography
  - tinycss2
  - ua-parser
  - cerberus
  - bytecode
  - pip
  - tzlocal
  - itsdangerous
  - datadog
  - dataclasses-json
  - pysolr
  - autopep8
  - ftfy
  - python-dotenv
  - xlsxwriter
  - constantly
  - asynctest
  - sqlalchemy
  - bleach
  - yamale
  - flask-babel
  - pandocfilters
  - graphene
  - python-gnupg
  - cached-property
  - py
  - environ-config
  - pydantic
  - astor
  - gast
  - tenacity
  - flask-cors
  - markdown-it-py
  - numpy
  - amply
  - formulaic
  - geopy
  - seaborn
  - geoalchemy2
  - pathable
  - statsmodels
  - executing
  - exceptiongroup
  - docker-pycreds
  - txaio
  - markdown
  - apeye-core
  - pycodestyle
  - setuptools-rust
  - alembic
  - jsons
  - anyconfig
  - multitasking
  - ipywidgets
  - black
  - cachey
  - python-monkey-business
  - dynesty
  - contextlib2
  - atlassian-python-api
  - credstash
  - intervaltree
  - pycobertura
  - fatpack
  - bincopy
  - proto-plus
  - xmltodict
  - django-model-utils
  - django-leaflet
  - google-apitools
  - httpcore
  - bidict
  - pgeocode
  - wcwidth
  - django-js-asset
  - msal
  - texttable
  - mockito
  - dunamai
  - litecli
  - isort
  - vine
  - backoff
  - django-stubs
  - mistune
  - pip-tools
  - django-extra-views
  - more-itertools
  - typer
  - setuptools-scm
  - imap-tools
  - azure-mgmt-datafactory
  - flake8-isort
  - sphinx-argparse
  - azure-mgmt-compute
  - invoke
  - django-nested-admin
  - pygithub
  - typing
  - formencode
  - ntlm-auth
  - wrapt
  - gspread
  - django-sql-explorer
  - environs
  - blinker
  - configargparse
  - urllib3
  - authlib
  - blacken-docs
  - json5
  - conda-pack
  - cloudsplaining
  - gdown
  - jsx-lexer
  - singledispatch
  - marshmallow
  - latexcodec
  - ipython_genutils
  - aiostream
  - django-pandas
  - cachetools
  - pipenv
  - macholib
  - swagger-spec-validator
  - tldextract
  - scikit-image
  - send2trash
  - azure-datalake-store
  - h11
  - parsedatetime
  - nest-asyncio
  - aiomysql
  - dparse
  - django-filter
  - datasketch
  - social-auth-core
  - amqp
  - folium
  - prettytable
  - django-waffle
  - dvc-studio-client
  - django-appconf
  - envier
  - databases
  - deepdiff
  - asn1crypto
  - alabaster
  - pamqp
  - fs-s3fs
  - mdurl
  - kafka-python
  - binarytree
  - aiounittest
  - async_generator
  - icalendar
  - wheel
  - parse
  - pytest-runner
  - pgpy
  - escapism
  - funcy
  - deprecation-alias
  - watchtower
  - click
  - sqlalchemy-jsonfield
  - idna
  - azure-kusto-data
  - parameterized
  - platformdirs
  - zipp
  - scramp
  - django-select2
  - azure-mgmt-sql
  - unittest-xml-reporting
  - azure-mgmt-marketplaceordering
  - azure-mgmt-subscription
  - pem
  - exchange-calendars
  - boto
  - azure-mgmt-network
  - iniconfig
  - everett
  - mpmath
  - fqdn
  - pathspec
  - inflection
  - queuelib
  - absl-py
  - oauth2client
  - azure-mgmt-containerinstance
  - leather
  - ordered-set
  - botocore
  - adal
  - flask
  - django-braces
  - atomicwrites
  - argcomplete
  - dramatiq
  - astropy
  - flake8-requirements
  - toolz
  - cloudpathlib
  - pandas-datareader
  - imagehash
  - structlog
  - dpath
  - terminaltables
  - parsel
  - aiofiles
  - dj-database-url
  - serde
  - hexbytes
  - behave-django
  - matplotlib
  - domdf-python-tools
  - ipython
  - requests-aws4auth
  - fastcore
  - pyjwt
  - flask-swagger-ui
  - uritools
  - tblib
  - scikit-learn
  - canopen
  - azure-mgmt-core
  - olefile
  - django-safedelete
  - flake8-annotations
  - antlr4-python3-runtime
  - tomli
  - msrestazure
  - pyproject_hooks
  - roundrobin
  - uncertainties
  - slack-sdk
  - kiwisolver
  - snowballstemmer
  - looker-sdk
  - websocket-client
  - rfc3986
  - python-utils
  - opt-einsum
  - pysocks
  - setuptools
  - flit
  - azure-storage-queue
  - python3-openid
  - python-multipart
  - sympy
  - smart-open
  - cfn-lint
  - azure-storage-file-share
  - parso
  - ecdsa
  - django-crispy-forms
  - azure-synapse-spark
  - anytree
  - astunparse
  - aioitertools
  - locket
  - azure-batch
  - overrides

 
