name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - bqplot
  - altair
  - ipydatagrid
  - plotly
  - matplotlib
  - numpy
  - pillow
  - ipywidgets
  - openpyxl
  - pandas <2
  - pycountry
  - scikit-learn
  - seaborn
  - sqlalchemy
  - vega_datasets
