[project]
name = "xeus-me"
version = "0.1.0"
description = "Setup a pixi environment for building a jupyterlite app with WASM"
authors = ["bugsbunny88 <bugs@bunny>"]
platforms = ["emscripten-wasm32", "osx-arm64", "osx-64", "linux-64"] # Windows is not working yet: "win-64"]
channels = ["conda-forge"]

[feature.wasm]
# add the emscripten-forge channel to the list of channels
channels = ["https://repo.mamba.pm/emscripten-forge"]
platforms = ["emscripten-wasm32"]

[feature.wasm.dependencies]
# we always need the xeus-python kernel for jupyterlite
xeus-python = "*"
python = "*"
# add any extra packages from emscripten-forge here
ipywidgets  = ">=8.1.5,<9"
matplotlib  = "==3.5.2"
numpy       = "==1.25.2"
openpyxl    = ">=3.0.9,<4"
orjson      = ">=3.10.6,<4"
pandas      = "==1.5.3"
plotly      = ">=5.24.1"
requests    = ">=2.32.3,<3"
scipy       = "==1.11.1"
seaborn     = ">=0.13.2,<0.14"
# new
typer       = ">=0.19.2,<0.20"
tqdm        = ">=4.67.1,<5"
toolz       = ">=1.0.0,<2"
tenacity    = ">=9.1.2,<10"
sympy = ">=1.14.0,<2"
swiglpk = ">=5.0.10,<6"
sqlglot = ">=27.20.0,<28"
seaborn = ">=0.13.2,<0.14"
scipy = "==1.11.1"
scikit-learn = ">=1.1.3,<2"
rich = ">=14.1.0,<15"
requests = ">=2.32.3,<3"
pytz = ">=2025.2,<2026"
pygad = ">=3.5.0,<4"
pydantic = ">=2.8.2,<3"
pyaml = ">=25.7.0,<26"
plotly = ">=6.3.0,<7"
pillow = ">=10.3.0,<11"
peewee = ">=3.17.3,<4"
pathspec = ">=0.12.1,<0.13"
param = ">=2.2.0,<3"
pandas = "==1.5.3"
orjson = ">=3.10.6,<4"
optlang = ">=1.8.2,<2"
openpyxl = ">=3.0.9,<4"
numpy = "==1.25.2"
networkx = ">=3.2,<4"
nbformat = ">=5.10.4,<6"
mlxtend = ">=0.23.4,<0.24"
matplotlib = ">=3.5,<3.9"
marshmallow = ">=3.26.1,<4"
lxml = ">=4.9.4,<5"
langgraph = ">=0.2.28,<0.3"
jupytext = ">=1.17.3,<2"
jsonschema = ">=4.17.3,<5"
json5 = ">=0.12.1,<0.13"
joblib = ">=1.4.0,<2"
ipywidgets = ">=8.1.7,<9"
folium = ">=0.20.0,<0.21"
fastcore = ">=1.8.12,<2"
dynaconf = ">=3.2.11,<4"
diskcache = ">=5.6.3,<6"
deepdiff = ">=8.6.1,<9"
click = ">=8.3.0,<9"
burr = ">=0.40.2,<0.41"
bs4 = ">=4.14.2,<5"
beartype = ">=0.22.2,<0.23"
autograd = ">=1.8.0,<2"
arrow = ">=1.3.0,<2"
altair = ">=5.5.0,<6"

[feature.host]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]
dependencies = { python = "*", jupyterlite-xeus = ">=2.0.0,<3", jupyter_server = "*" }

# make sure that we have the WASM environment installed before building the app
[feature.host.tasks]
setup-wasm = { cmd = "pixi install -e wasm", inputs = ["pixi.lock"] }
build-dist = { cmd = "pixi run build --output-dir dist" }

# build the jupyterlite app
[feature.host.tasks.build]
cmd = "jupyter lite build --XeusAddon.prefix=.pixi/envs/wasm"
depends-on = ["setup-wasm"]
outputs = ["_output"]
inputs = ["pixi.lock", "files/"]

# serve the jupyterlite app with a "simple server"
[feature.host.tasks.start]
cmd = "python -m http.server 8000 -d _output"
depends-on = ["build"]

[environments]
default = ["host"]
wasm = ["wasm"]
